### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Yohoki** [Yohoki/Savegame-Profile-Switcher#1]
My goal with this program is to remove my mouse and keyboard from my family gaming station, without removing the functionality. Many games don't have multiple profiles anymore, so multiple family members have to play on the same profile. This has been fixed with the profile swapper.

My next goals are to get multiple profiles working (3+) and to incorporate emulator config files into the mix, for games that have specific controller/plugin needs.

Current Tasks
- [ ] Add multiple profiles for games (ie, unlimited named profiles instead of "Profile2")
- [x] Add function to add a new profile
- [ ] Add or test functions with emulator config files and controller settings

Completed Tasks:
- [x] Add Headless Mode
Added in v2.0 before adding to Github
- [x] Add function to add new games within program
Finished 7/26/2019
Includes check for GameID in .ini file before creating new profile.
